Develop menuitem
portalium/yii2-notification pull request #28
Opened 2024-07-31 15:49 UTC by irmakyuceak

2024-08-01 04:39 UTC, uguryildiz requested changes
Menu Item width must be same size to other items. However sub-menu width can be more than root menu items. You can review for sample on profile widget.

2024-08-02 06:58 UTC, irmakyuceak commented
item size changed

2024-08-02 09:39 UTC, uguryildiz requested changes
Please check messages.

2024-08-02 09:39 UTC, uguryildiz commented on src/widgets/views/notifications.php
>                  <h6 class="dropdown-header">No Notifications</h6>
"No Notifications" header must change as "Notifications"

2024-08-05 11:58 UTC, uguryildiz approved these changes

2024-08-05 11:58 UTC, merged